name: build and test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: Setup Bazel environment
        uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-cache: true
          disk-cache: ${{ github.workflow }}
          repository-cache: true
      - name: setup Docker Buildx
        run: docker/setup-buildx-action@v3
      - name: build docker image
        run: docker build -f Dockerfile -t cpp-analytics-devops:v1 .
      - name: run docker container tests (docker image run in the background)
        run: |
          docker run -d -p 8080:8080 cpp-analytics-devops:v1
          sleep 5
          curl --fail --show-error --silent "http://127.0.0.1:8080/factorize?number=1000" || echo "API request failed."
          sleep 5
          curl --fail --show-error --silent "http://127.0.0.1:8080/simulate/pi?iterations=1000000" || echo "API request failed."